# Generated by Django 4.1 on 2022-08-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('table_num', models.PositiveSmallIntegerField()),
                ('pos_x', models.IntegerField(blank=True, null=True)),
                ('pos_y', models.IntegerField(blank=True, null=True)),
                ('reserved', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.table'),
        ),
    ]
