# Generated by Django 4.1.4 on 2023-02-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('hero_title', models.CharField(max_length=40)),
                ('about_us', models.TextField()),
                ('about_us_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('pizza_chef_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('pizza_chef_name', models.CharField(max_length=50)),
                ('pizza_chef_desc', models.TextField()),
                ('pizza_chef_quote', models.TextField()),
                ('our_dishes_text', models.TextField()),
                ('pizza_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('pizza_text', models.TextField()),
                ('panino_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('panino_text', models.TextField()),
                ('desert_image', models.ImageField(null=True, upload_to='settings_img/')),
                ('desert_text', models.TextField()),
                ('street_name', models.CharField(max_length=60)),
                ('street_num', models.CharField(max_length=10)),
                ('postal_and_city', models.CharField(max_length=20)),
                ('open_mo_fr', models.CharField(max_length=30)),
                ('open_sat', models.CharField(max_length=30)),
                ('open_sun', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=50)),
                ('instagram_link', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
