# Generated by Django 4.1 on 2022-08-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_table_product_allergens_product_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_menu',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
