# Generated by Django 4.1 on 2022-08-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_on_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
