# Generated by Django 4.1.1 on 2022-09-22 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('tbl', 'Tisch'), ('taw', 'Take Away'), ('tel', 'Telefonisch'), ('onl', 'Online')], max_length=3)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=55)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='table',
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Open'), ('A', 'Accepted'), ('C', 'Canceled'), ('D', 'Done')], default='O', max_length=1),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
    ]
