# Generated by Django 4.1.1 on 2022-11-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('O', 'Open'), ('A', 'Accepted'), ('C', 'Canceled'), ('D', 'Done')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('sum', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_time',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('tbl', 'Tisch'), ('taw', 'Take Away'), ('tel', 'Phone'), ('onl', 'Online')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.client'),
        ),
    ]
