# Generated by Django 4.1 on 2022-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_fr', models.CharField(max_length=20)),
                ('sa', models.CharField(max_length=20)),
                ('so', models.CharField(max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=80, null=True)),
                ('instagram', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.CharField(max_length=50)),
                ('hero_desc', models.TextField(blank=True, null=True)),
                ('hero_btn_text', models.CharField(max_length=30)),
                ('hero_btn_url', models.CharField(blank=True, max_length=80, null=True)),
                ('about_us_img', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('about_us', models.TextField(blank=True)),
                ('chef_name', models.CharField(max_length=80)),
                ('chef_desc', models.TextField(blank=True, null=True)),
                ('chef_quote', models.TextField(blank=True, null=True)),
                ('chef_img', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('dishes_desd', models.TextField(blank=True, null=True)),
                ('pizza_img', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('pizza_desc', models.TextField(blank=True, null=True)),
                ('panino_desc', models.TextField(blank=True, null=True)),
                ('panino_img', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('desert_img', models.ImageField(blank=True, null=True, upload_to='page/')),
                ('desert_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
