# Generated by Django 4.1 on 2022-09-16 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_homepage_settings_hero_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage_settings',
            name='hero_img',
        ),
    ]
