name: CiboColorato

on:
  push:
    branches: [production]

jobs:
  deployment:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Repository copy
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/k006679/cibo_server/"

  dependencies:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/k006679/cibo_server
            pip install -r requirements.txt
            python manage.py migrate
            cd /frontend
            npm install

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Running tests
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/k006679/cibo_server
            python manage.py test
 
  booting:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Booting cibo_server
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/k006679/cibo_server
            pkill gunicorn
            gunicorn -c config/gunicorn/prod.py
            cd /frontend
            npm run build
            sudo systemctl restart nginx
            sudo systemctl status nginx